site_name: Datawarehousing for BI specialization (University of Colorado)
nav:
  - Home: index.md
  - Database Management Essentials:
          - Relational Data Model and Create Table Statement: week1.md
theme: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
