CREATE TABLE Customer(
custno CHAR(4) CONSTRAINT NOT NULL,
custname VARCHAR(30) CONSTRAINT NOT  NULL,
address VARCHAR(30) CONSTRAINT NOT NULL,
Internal CAHR(1) CONSTRAINT NOT NULL,
CONSTRAINT PRIMARY KEY (custno)
)
